# Generated by Django 3.1.6 on 2021-02-22 06:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TechnicalCourses', '0003_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 22, 6, 14, 11, 469137, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
